---
- name: Run my_roles on localhost
  hosts: desk
  roles:
    - { role: user, tags: [ 'user', 'config' ] }
    - { role: update, tags: [ 'update', 'config' ] }
    - { role: homebrew, tags: [ 'homebrew', 'config' ] }
    - { role: bash, tags: [ 'bash', 'config' ] }
    - { role: starship, tags: [ 'starship', 'config' ] }
    - { role: fzf, tags: [ 'fzf', 'config' ] }
    - { role: neovim, tags: [ 'neovim', 'config' ] }
    - { role: fonts, tags: [ 'fonts', 'config' ] }
    - { role: orbstack, tags: [ 'orbstack', 'config' ] }
    - { role: spotify, tags: [ 'spotify', 'config' ] }
    - { role: lsd, tags: [ 'lsd', 'config' ] }
    - { role: raycast, tags: [ 'raycast', 'install' ] }
    - { role: gh, tags: [ 'gh', 'install' ] }
    - { role: dock, tags: [ 'dock', 'install' ] }
    - { role: docker, tags: [ 'docker', 'install' ] }
